
spring:
# SPRING MVC (WebMvcProperties)
  mvc:
    async:
      request-timeout: 300 # Amount of time (in milliseconds) before asynchronous request handling times out.
    date-format: dd/MM/yyyy # Date format to use. For instance `dd/MM/yyyy`.
    dispatch-trace-request: false # Dispatch TRACE requests to the FrameworkServlet doService method.
    dispatch-options-request: true # Dispatch OPTIONS requests to the FrameworkServlet doService method.
    favicon:
      enabled: true # Enable resolution of favicon.ico.
    formcontent:
      putfilter:
        enabled: true # Enable Spring's HttpPutFormContentFilter.
    ignore-default-model-on-redirect: true # If the content of the "default" model should be ignored during redirect scenarios.
    #locale: es_ES # Locale to use. By default, this locale is overridden by the "Accept-Language" header.
    #locale-resolver: accept-header # Define how the locale should be resolved.
    #log-resolved-exception: false # Enable warn logging of exceptions resolved by a "HandlerExceptionResolver".
    #media-types.*: # Maps file extensions to media types for content negotiation.
    #message-codes-resolver-format: # Formatting strategy for message codes. For instance `PREFIX_ERROR_CODE`.
    #servlet:
      #load-on-startup: -1 # Load on startup priority of the Spring Web Services servlet.
    static-path-pattern: /** # Path pattern used for static resources.
    throw-exception-if-no-handler-found: false # If a "NoHandlerFoundException" should be thrown if no Handler was found to process a request.
    #view:
      #prefix: # Spring MVC view prefix.
      #suffix: # Spring MVC view suffix.
###########################################################################
# THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    cache: true # Enable template caching.
    check-template: true # Check that the template exists before rendering it.
    check-template-location: true # Check that the templates location exists.
    content-type: text/html # Content-Type value.
    enabled: true # Enable MVC Thymeleaf view resolution.
    encoding: ISO-8859-1 #UTF-8 # Template encoding.
    excluded-view-names:  # Comma-separated list of view names that should be excluded from resolution.
    mode: HTML5 # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
    suffix: .html # Suffix that gets appended to view names when building a URL.
    template-resolver-order:  # Order of the template resolver in the chain.
    view-names:  # Comma-separated list of view names that can be resolved.
    
# BANNER
banner:
  charset: UTF-8 # Banner file encoding.
  location: classpath:banner.txt # Banner file location.
  image:
    location: classpath:banner.gif # Banner image file location (jpg/png can also be used).
    #width:  # Width of the banner image in chars (default 76)
    #height:  # Height of the banner image in chars (default based on image height)
    #margin:  # Left hand image margin in chars (default 2)
    #invert:  # If images should be inverted for dark terminal themes (default false)